### ISSUE TITLE
Highlighting of code blocks

### ISSUE THREAD

**Issue by rwols** [tonsky/sublime-scheme-writer#1]
Code blocks are missing their highlighting:

<img width="658" alt="image" src="https://user-images.githubusercontent.com/2431823/110203533-0547e700-7e6f-11eb-9e68-bb041208a240.png">

Compare with Mariana:

<img width="658" alt="image" src="https://user-images.githubusercontent.com/2431823/110203561-23ade280-7e6f-11eb-95ee-23fad14fb7bd.png">

**Comment by tonsky** [comment]
That’s by design, exactly as in iA Writer

**Comment by nlopin** [comment]
To me, the background of the code block should not go out of the central column. I tried to fix it, but couldn't find any option that handles this is ST4.

Unfortunately, it is a [5-year-old reported issue](https://github.com/sublimehq/sublime_text/issues/1787).
